### ISSUE TITLE
曜日の修正

### ISSUE THREAD

**Issue by kou029w** [RustyNail/page_object_pattern_demo#5]
https://github.com/RustyNail/page_object_pattern_demo/blob/71eca79eaa5d823f902707cee6725af9a0ae2007/spec/reservation_confirm_spec.rb#L21

**Comment by RustyNail** [comment]
Fixed with https://github.com/RustyNail/page_object_pattern_demo/commit/9794b7b71135c16700e66cdb27fdac0b0f903e77
