### ISSUE TITLE
チュートリアル用のブランチ作成&不要なファイル削除

### ISSUE THREAD

**Issue by RustyNail** [RustyNail/page_object_pattern_demo#7]
## 変更
- [ブランチ](https://github.com/RustyNail/page_object_pattern_demo/tree/tutorial)
  - [差分](https://github.com/RustyNail/page_object_pattern_demo/commit/b6f18ac9d49f8d1887bf0399eb08e0956cd8f54d)

**Comment by RustyNail** [comment]
ブランチ作りました。
レビューお願いします。 @kou029w

**Comment by kou029w** [comment]
![LGTM](http://www.lgtm.in/p/uDsXmLjzs)
